
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axdywblewdfoeqirsfww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZHl3Ymxld2Rmb2VxaXJzZnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjQwOTQsImV4cCI6MjA2MDE0MDA5NH0.XbAgYDw2mjkHcjSjYmdMOqHTTUpqssBGPGaYWpUMeUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
